# Generated by Django 2.2 on 2020-02-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet_Cash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('avail_date', models.DateField()),
                ('source_sum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Wallet_Credit_Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('avail_date', models.DateField()),
                ('source_sum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Wallet_Deb_Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('avail_date', models.DateField()),
                ('source_sum', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Total',
        ),
        migrations.RemoveField(
            model_name='wallets',
            name='user',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.DeleteModel(
            name='Wallets',
        ),
    ]
