# Generated by Django 2.2 on 2020-02-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_auto_20200219_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('balance', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Wallet_Cash',
        ),
        migrations.DeleteModel(
            name='Wallet_Credit_Card',
        ),
        migrations.DeleteModel(
            name='Wallet_Deb_Card',
        ),
    ]
