# Generated by Django 2.2 on 2020-02-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_auto_20200224_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterModelTable(
            name='wallet',
            table='Wallets',
        ),
    ]
